name: Deploy Hugo Website

on:
  push:
    branches:
      - main # or any other branch you use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3' # Use latest stable version

      - name: Build Website
        run: hugo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          
      - name: upload build files(optional step)
        uses: actions/upload-artifact@v3
        with:
          name: hugo-site
          path: public
